signalfx:
  endpoint: https://ingest.signalfx.com
  access_token:    
  timeout: 4        #in seconds
  stats_interval: 5 #in seconds

splunk:
  splunkHost: 
  splunkPort: 443
  splunkToken:  
  splunkIndex: main
  timeout: 4        #in seconds
  stats_interval: 5 #in seconds

aws:
  aws_access_key_id:  
  aws_secret_access_key:   
  new_lambda_role:  
  memory_size: 1024 #Mb
  #aws_session_token: SESSION_TOKEN